# Numpy arrays

A numpy array is a multidimensional array of numbers. It is a data structure that is used to store and manipulate numerical data in a structured way. Numpy arrays look like lists, but they are more efficient and have more features:

In [2]:
import numpy as np

list1 = [3.2, 5.5, 10.1]
list2 = [3.2, 11.3, 0.3] 

# Create two 1-dimensional (1D) arrays
# with the elements of the above lists
array1 = np.array(list1)
array2 = np.array(list2)

print("array1:", array1)
print()
print("array2:", array2)

array1: [ 3.2  5.5 10.1]

array2: [ 3.2 11.3  0.3]


The above code creates two numpy arrays from lists. This is done using the `np.array()` function. Let us add the lists and add the numpy arrays:

In [3]:
print("Adding lists:", list1 + list2)

print("Adding numpy arrays:", array1 + array2)

Adding lists: [3.2, 5.5, 10.1, 3.2, 11.3, 0.3]
Adding numpy arrays: [ 6.4 16.8 10.4]


Notice that adding lists concatenates lists, while adding numpy arrays adds the elements of the arrays.

Each numpy array has a shape, which is the number of elements in each dimension:

In [4]:
list1 = [3.2, 5.5, 10.1]

list2 = [
    [3.2, 11.3, 0.3],
    [1.1, 2.2, 3.3]
]

array1 = np.array(list1)
array2 = np.array(list2)

print("array1:", "shape: ", array1.shape, "size: ", array1.size)
print()
print("array2:", "shape: ", array2.shape, "size: ", array2.size)

array1: shape:  (3,) size:  3

array2: shape:  (2, 3) size:  6


A two dimensional numpy array has two dimensions. The first dimension is the number of rows, and the second dimension is the number of columns. The axis of a two dimensional array is 0 for the first dimension and 1 for the second dimension. We can access the elements of a two dimensional array using the index operator `[]`. The first index is the row index and the second index is the column index:

In [5]:
list1 = [
    [3.2, 11.3, 0.3],
    [1.1, 2.2, 3.3]
]

array1 = np.array(list1)
print("Element in row 0 and column 1:", array1[0, 1])
print("Element in row 1 and column 2:", array1[1, 2])

Element in row 0 and column 1: 11.3
Element in row 1 and column 2: 3.3


## More ways to create numpy arrays

In addition to creating numpy arrays using the `np.array` function, numpy also provides a number of functions for creating arrays of different shapes and types:

In [6]:
#create a 3x2 array with all elements 7
array1 = np.full((3, 2), 7)
print("array1:\n", array1, "\nshape: ", array1.shape, "size: ", array1.size)
print()
# Create a 4x2 array with all elements 0
array2 = np.zeros((4, 2))
print("array2:\n", array2, "\nshape: ", array2.shape, "size: ", array2.size)
print()
# Create a 2x5 array with all elements 1
array3 = np.ones((2, 5))
print("array3:\n", array3, "\nshape: ", array3.shape, "size: ", array3.size)


array1:
 [[7 7]
 [7 7]
 [7 7]] 
shape:  (3, 2) size:  6

array2:
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]] 
shape:  (4, 2) size:  8

array3:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 
shape:  (2, 5) size:  10


It is also possible to sort an array:

In [13]:
array1 = np.array([2, 4, 1, 3])
array1.sort()
print(array1)

[1 2 3 4]


We can also change the shape of an array using the `reshape` method:

In [7]:
#create a 3x2 array with all elements 7
array1 = np.full((3, 4), 7)
print("array1:\n", array1, "\nshape: ", array1.shape, "size: ", array1.size)
print()
array2 = array1.reshape((2, 6))
print("array2:\n", array2, "\nshape: ", array2.shape, "size: ", array2.size)


array1:
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]] 
shape:  (3, 4) size:  12

array2:
 [[7 7 7 7 7 7]
 [7 7 7 7 7 7]] 
shape:  (2, 6) size:  12


We can also flatten the array into a 1D array:

In [ ]:
#create a 2x3 array with all elements 7
array1 = np.array([[3.2, 11.3, 0.3], [1.1, 2.2, 3.3]])
print("array1:\n", array1, "\nshape: ", array1.shape, "size: ", array1.size)
print()
array2 = array1.ravel()
print("array2:\n", array2, "\nshape: ", array2.shape, "size: ", array2.size)


array1:
 [[ 3.2 11.3  0.3]
 [ 1.1  2.2  3.3]] 
shape:  (2, 3) size:  6

array2:
 [ 3.2 11.3  0.3  1.1  2.2  3.3] 
shape:  (6,) size:  6


Finally, a frequent operation is to transpose an array, which basically means converting the rows to columns:

In [19]:
array1 = np.array([[3.2, 11.3, 0.3], [1.1, 2.2, 3.3]])
print("array1:\n", array1, "\nshape: ", array1.shape, "size: ", array1.size)
print()
array2 = array1.transpose()
print("array2:\n", array2, "\nshape: ", array2.shape, "size: ", array2.size)

array1:
 [[ 3.2 11.3  0.3]
 [ 1.1  2.2  3.3]] 
shape:  (2, 3) size:  6

array2:
 [[ 3.2  1.1]
 [11.3  2.2]
 [ 0.3  3.3]] 
shape:  (3, 2) size:  6


## Mathemaatical operations

We saw that when we add two arrays, we add the corresponding elements. This is called element-wise addition. We can also do element-wise multiplication, division, and subtraction:

In [9]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

print("array1:\n", array1)
print()
print("array2:\n", array2)
print()
print("Adding arrays:")
print(array1 + array2)
print()
print("Subtracting arrays:")
print(array1 - array2)
print()
print("Multiplying arrays:")
print(array1 * array2)
print()
print("Dividing arrays:")
print(array1 / array2)

array1:
 [[1 2 3]
 [4 5 6]]

array2:
 [[ 7  8  9]
 [10 11 12]]

Adding arrays:
[[ 8 10 12]
 [14 16 18]]

Subtracting arrays:
[[-6 -6 -6]
 [-6 -6 -6]]

Multiplying arrays:
[[ 7 16 27]
 [40 55 72]]

Dividing arrays:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


We can also use mathematical functions on arrays:

In [30]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
print("array1:\n", array1)
print()
print()
print("Square root")
print(np.sqrt(array1))
print()
print("Maximum")
print(np.max(array1))
print()
print("Minimum")
print(np.min(array1))
print()
print("Mean")
print(np.mean(array1))

array1:
 [[1 2 3]
 [4 5 6]]


Square root
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]

Maximum
6

Minimum
1

Mean
3.5


Finally, we can perform dot product multiplication, on the two arrays:

In [31]:
array1 = np.array([1, 2, 3])
array2 = np.array([7, 8, 9])

print("array1:\n", array1)
print()
print("array2:\n", array2)
print()
print("Dot product")
print(np.dot(array1, array2))

array1:
 [1 2 3]

array2:
 [7 8 9]

Dot product
50


Finding the dot product for one dimensional arrays means finding the sum of the products of the corresponding elements.